export const RIVER_HOLDEM_ADDRESS = (process.env.NEXT_PUBLIC_RIVER_HOLDEM_ADDRESS ||
  "") as `0x${string}`;

export const riverHoldemAbi = [
  {
    type: "function",
    name: "createTable",
    stateMutability: "payable",
    inputs: [],
    outputs: [{ name: "tableId", type: "uint256" }],
  },
  {
    type: "function",
    name: "joinTable",
    stateMutability: "payable",
    inputs: [{ name: "tableId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "startNextHand",
    stateMutability: "payable",
    inputs: [{ name: "tableId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "fold",
    stateMutability: "nonpayable",
    inputs: [{ name: "tableId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "checkCall",
    stateMutability: "nonpayable",
    inputs: [{ name: "tableId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "raiseTo",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tableId", type: "uint256" },
      { name: "totalBet", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitShowdownCard",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tableId", type: "uint256" },
      { name: "slot", type: "uint8" },
      { name: "value", type: "uint256" },
      { name: "sigs", type: "bytes[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeShowdown",
    stateMutability: "nonpayable",
    inputs: [{ name: "tableId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cashOut",
    stateMutability: "nonpayable",
    inputs: [{ name: "tableId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getHoleHandles",
    stateMutability: "view",
    inputs: [{ name: "tableId", type: "uint256" }],
    outputs: [
      { type: "bytes32" },
      { type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "getBoardHandles",
    stateMutability: "view",
    inputs: [{ name: "tableId", type: "uint256" }],
    outputs: [
      { name: "out", type: "bytes32[5]" },
      { name: "count", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "tables",
    stateMutability: "view",
    inputs: [{ name: "tableId", type: "uint256" }],
    outputs: [
      { name: "player0", type: "address" },
      { name: "player1", type: "address" },
      { name: "buyIn", type: "uint256" },
      { name: "stack0", type: "uint256" },
      { name: "stack1", type: "uint256" },
      { name: "pot", type: "uint256" },
      { name: "bet0", type: "uint256" },
      { name: "bet1", type: "uint256" },
      { name: "currentBet", type: "uint256" },
      { name: "button", type: "uint8" },
      { name: "toAct", type: "address" },
      { name: "stage", type: "uint8" },
      { name: "folded0", type: "bool" },
      { name: "folded1", type: "bool" },
      { name: "boardCount", type: "uint8" },
      { name: "handLive", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "deckFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "n", type: "uint16" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "fundFees",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "MIN_BUY_IN",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "event",
    name: "TableCreated",
    inputs: [
      { name: "tableId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "buyIn", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "HandSettled",
    inputs: [
      { name: "tableId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
      { name: "pot", type: "uint256", indexed: false },
    ],
  },
] as const;

export const STAGE_LABELS = [
  "Waiting",
  "Preflop",
  "Flop",
  "Turn",
  "River",
  "Showdown",
  "Settled",
] as const;
